### ISSUE TITLE
Error on docker or native python

### ISSUE THREAD

**Issue by rachid598** [ShaneIsrael/plex-auto-genres#11]
Hello,
I discover your tool yesterday and i try it today.
But i follow the instruction and i have the same error on docker and native python.
I attach my error.

I guess you you forgot in docker-compose.yml the " version: 'XX'"

Can someone help me
<img width="858" alt="python" src="https://user-images.githubusercontent.com/46326588/105465254-f7f5e500-5c92-11eb-9db2-93cad807d95a.PNG">

**Comment by darkknight6722** [comment]
Post your config.json. You are missing `,` in that mentioned place.

**Comment by rachid598** [comment]
> Post your config.json. You are missing `,` in that mentioned place.
I use the config.example
Thanks

{
    "general_settings": {
        "genres": {
            "standard-tv": {
                "ignore": [],
                "replace": {}
            },
            "standard-movie": {
                "ignore": ["TV Movie"],
                "replace": {}
            },
            "anime": {
                "ignore": ["ignore this genre", "kids", "seinen", "police"],
                "replace": {
                    "the genre to replace": "value to replace with",
                    "shoujo ai": "shoujo",
                    "shounen ai": "shounen"
                }
            }
        }
    },
    "automation_settings": {
        "run": [
            {
                "library": "Films",
                "type": "standard-movie",
                "setPosters": true
            },
            {
                "library": "Anime Shows",
                "type": "anime",
                "setPosters": false
            },
            {
                "library": "Series",
                "type": "standard-tv",
                "setPosters": true
            }
            {
                "library": "some other library",
                "type": "some other type",
                "setPosters": "upload cover art located in /posters?"
            }
        ]
    }
}

**Comment by rachid598** [comment]
I add a comma line 38 and it's work ;)

**Comment by ShaneIsrael** [comment]
Hmm. Looks to be an issue in python 3.6 and 3.7 with how I'm using regex. I'll try to get a fix out real quick for that error. I'm not sure what you mean though about collections in french?

**Comment by rachid598** [comment]
> Hmm. Looks to be an issue in python 3.6 and 3.7 with how I'm using regex. I'll try to get a fix out real quick for that error. I'm not sure what you mean though about collections in french?

Thank you very much. 
For the french collections 
Its possible to translate the name of collection. 
Like i have adventure and i want aventure. 
Comedy i want comédie 
Horor i want horreur etc....

**Comment by ShaneIsrael** [comment]
Okay so I pushed up a hopeful fix for that \u error you were seeing. Pull down the changes and try it. 

For the french translation, let me do a little research here and I'll get back to you.

**Comment by rachid598** [comment]
> Okay so I pushed up a hopeful fix for that \u error you were seeing. Pull down the changes and try it.
> 
> For the french translation, let me do a little research here and I'll get back to you.

Thank you very much 👍🏻

**Comment by ShaneIsrael** [comment]
So the best way to accomplish what your looking for is to use the replace functionality that I have built into the docker version. Which you are using so thats good.

So in your config.json you just need to add some entries to the replace section under the `genre` settings. 

You would just update your standard-tv, standard-movie and anime sections (whichever you want the translations in) to something like this

```            
"standard-tv": {
      "ignore": [],
      "replace": {
        "comedy": "comédie",
        "horror": "horreur",
        "english_genre": "french_translate"
      }
  },
  "standard-movie": {
      "ignore": ["TV Movie"],
      "replace": {
         "comedy": "comédie",
         "horror": "horreur",
         "english_genre": "french_translate"
      }
  },
 ```
 
 Once you make this change with all the genre translates. Try this and let me know if there's any issues.

**Comment by rachid598** [comment]
> So the best way to accomplish what your looking for is to use the replace functionality that I have built into the docker version. Which you are using so thats good.
> 
> So in your config.json you just need to add some entries to the replace section under the `genre` settings.
> 
> You would just update your standard-tv, standard-movie and anime sections (whichever you want the translations in) to something like this
> 
> ```
> "standard-tv": {
>       "ignore": [],
>       "replace": {
>         "comedy": "comédie",
>         "horror": "horreur",
>         "english_genre": "french_translate"
>       }
>   },
>   "standard-movie": {
>       "ignore": ["TV Movie"],
>       "replace": {
>          "comedy": "comédie",
>          "horror": "horreur",
>          "english_genre": "french_translate"
>       }
>   },
> ```
> 
> Once you make this change with all the genre translates you'll have to go through and delete any english collections that still exist since new ones will be made. Try this and let me know if there's any issues.

Thank you very much for your Quick response. 
I will try tomorow 👍🏻

**Comment by ShaneIsrael** [comment]
My example was kinda bad. 

On the replace section, make sure you capitalize the first letter since TMDB always gives the genres starting with a capital letter and if you leave it lowercase it will not hit.

 ```
 "standard-tv": {
       "ignore": [],
       "replace": {
         "Comedy": "comédie",
         "Horror": "horreur",
         "English_genre": "french_translate"
       }
   },
   "standard-movie": {
       "ignore": ["TV Movie"],
       "replace": {
          "Comedy": "comédie",
          "Horror": "horreur",
          "English_genre": "french_translate"
       }
   },
 ```

**Comment by rachid598** [comment]
> My example was kinda bad.
> 
> On the replace section, make sure you capitalize the first letter since TMDB always gives the genres starting with a capital letter and if you leave it lowercase it will not hit.
> 
> ```
> "standard-tv": {
>       "ignore": [],
>       "replace": {
>         "Comedy": "comédie",
>         "Horror": "horreur",
>         "English_genre": "french_translate"
>       }
>   },
>   "standard-movie": {
>       "ignore": ["TV Movie"],
>       "replace": {
>          "Comedy": "comédie",
>          "Horror": "horreur",
>          "English_genre": "french_translate"
>       }
>   },
> ```
Thank you very much
It works great
![Plex](https://user-images.githubusercontent.com/46326588/105582724-37562b80-5d90-11eb-8350-9e03eb6cab70.PNG)
