### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Plasma21** [ShaneIsrael/plex-auto-genres#23]
Hi guys,

Trying this script on a Mac. I edited the .env file and changed the name on the config file. When running this command : python plex-auto-genres.py --library Movies --type standard -movie

I get the following error: 

  File "plex-auto-genres.py", line 21
    print(f'\nYou are about to update your {bcolors.WARNING}[{LIBRARY}]{bcolors.ENDC} collection\'s ratings with ratings from MyAnimeList.')
                                                                                                                                          ^
SyntaxError: invalid syntax

Thanks for your help.

**Comment by ShaneIsrael** [comment]
You're command is wrong. You have `standard -movie` when it should be `standard-movie` no space in it.

**Comment by ShaneIsrael** [comment]
`python plex-auto-genres.py --library Movies --type standard-movie`
