### ISSUE TITLE
no attribute 'collection'

### ISSUE THREAD

**Issue by mtauberjr** [ShaneIsrael/plex-auto-genres#25]
Traceback (most recent call last):
  File "/mnt/mpathae/mtauberjr/plex-auto-genres/plex-auto-genres.py", line 35, in <module>
    uploadCollectionArt(plex)
  File "/mnt/mpathae/mtauberjr/plex-auto-genres/src/plex.py", line 179, in uploadCollectionArt
    collections = plex.library.section(LIBRARY).collection()
AttributeError: 'MovieSection' object has no attribute 'collection'

**Comment by ShaneIsrael** [comment]
@mtauberjr Can you give me the exact command that you ran that produced that error?

**Comment by mtauberjr** [comment]
![Image 9-20-21 at 9 24 PM](https://user-images.githubusercontent.com/284211/134102463-60ff8c66-b8b3-4e54-a639-14c130335dd0.jpeg)
running this command. python plex-auto-genres.py --library Movies --type standard-movie --set-posters

**Comment by ShaneIsrael** [comment]
Do you have any collection created in that library on plex? Did you run the script first without the `--set-posters` so that it can create the collections?

**Comment by mtauberjr** [comment]
That worked!! Thank you so much!!  I ran it without --set-posters flag.  I did not have any collections made, so created some by hand when I saw that error.  However, I think it required a Plex Scan to run, because it worked the next day!
