### ISSUE TITLE
MAL made changes to genres and split in into demographics/themes

### ISSUE THREAD

**Issue by Icnopandaz** [ShaneIsrael/plex-auto-genres#28]
Since the changes am unable to scan through and add new items without 503 errors (very inconsistentally, sometimes it works, sometimes it doesn't, have to try multiple times and depends on luck):

Uncaught Exception: HTTP 503 - status=503, type=BadResponseException, message=Jikan failed to connect to MyAnimeList. MyAnimeList may be down/unavailable or refuses to connect, error=None for search type=anime, query=Attack on Titan←[0m
Updated 0 entrie(s) since last run.

Article for Change: https://myanimelist.net/forum/?topicid=1956762
Affected Code: https://github.com/ShaneIsrael/plex-auto-genres/blob/master/src/genres.py#L16-L17

**Comment by ShaneIsrael** [comment]
Yeah it's a little weird. I had that issue come up in my logs at one point so it seems sporadic. My guess is they have an issue in their v3 api somewhere which is what the jikanpy wrapper uses. Their v4 api is still in beta and the python wrapper devs won't upgrade it to the v4 until it's out of beta.
