### ISSUE TITLE
"The resource you requested could not be found"

### ISSUE THREAD

**Issue by leafsfan525** [ShaneIsrael/plex-auto-genres#3]
It seemed to be working fine but when I got to 40% through my library, I got a message saying "The resource you requested could not be found"

**Comment by ShaneIsrael** [comment]
I've made a couple changes that should hopefully help tell us what media entry is having the problem. The error does seem to come from TMDB. If the error happens it should print to the terminal screen but also keep progressing with the rest of your library. 

Please try the updated script and let me know what gets printed this time.
