### ISSUE TITLE
Subler Embedded Genre Tags

### ISSUE THREAD

**Issue by briangoodman** [ShaneIsrael/plex-auto-genres#30]
Shane, 

Many Plex users, myself included, use Subler to add metadata to movie files before importing them into the Plex movie library with the "Prefer local metadata" checked, in order to have more control over tags (especially genre tags) and posters. 

Is it possible to give plex-auto-genres its own "Prefer local metadata" feature, so that our embedded genre tags are used to create collections rather than a scan of TMDB?

Thanks,

Brian

**Comment by ShaneIsrael** [comment]
@briangoodman Sorry for the way late reply. Unfortunately that is not possible with plex-auto-genres. This tool doesn't look at your actual media files. It uses the Plex API to get info about your media and then update that info.
