### ISSUE TITLE
Error due to ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by Droppisalt** [ShaneIsrael/plex-auto-genres#31]
I have the following error in my logs after starting my docker container.
`standard_init_linux.go:228: exec user process caused: exec format error`
I believe this is due to me using it on a Raspberry Pi. Any image for ARM devices? Or am I stuck not being able to use it?

Thanks!

**Comment by ShaneIsrael** [comment]
You are completely free to build an arm based image of this project and use it. This is not something that is required of me to do.

**Comment by Droppisalt** [comment]
> You are completely free to build an arm based image of this project and use it. This is not something that is required of me to do.

I was only inquiring not requesting :) I would definitely build one if I had any knowledge. However, I've now moved to a non-ARM CPU and will be adding PMM to my server soon!
