### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Rhoadesma** [ShaneIsrael/plex-auto-genres#4]
I just did a pull and when trying to run it, I am getting the error below:

python plex-auto-genres.py --library "Movies" --type standard-movie
Traceback (most recent call last):
  File "plex-auto-genres.py", line 198, in <module>
    CONFIRMATION = "\nYou are about to create ["+bcolors.WARNING+args.type[0]+bcolors.ENDC+"] genre collection tags for the library ["+bcolors.WARNING+args.library[0]+bcolors.ENDC+"] on your server ["+bcolors.WARNING+PLEX_SERVER_NAME+bcolors.ENDC+"]."
TypeError: can only concatenate str (not "NoneType") to str

**Comment by ShaneIsrael** [comment]
You must have changed the PLEX_SERVER_NAME variable in the `.env` file or did not rename the `.env.example` file to `.env`.

**Comment by fdarveau** [comment]
If using Token authentication, the PLEX_SERVER_NAME is not required, so the CONFIRMATION message generates the error.

You should replace `["+bcolors.WARNING+PLEX_SERVER_NAME+bcolors.ENDC+"]."` with `["+bcolors.WARNING+(PLEX_SERVER_NAME or PLEX_BASE_URL)+bcolors.ENDC+"]."`

**Comment by ShaneIsrael** [comment]
@fdarveau Right you are, updating that now.
