### ISSUE TITLE
Crash at 15.4%

### ISSUE THREAD

**Issue by vaparr** [ShaneIsrael/plex-auto-genres#8]
I am unable to get passed 15.4%, with this crash:

root@Unraid:/tmp/plex-auto-genres# python3 ./plex-auto-genres.py --library Anime --type anime

Connecting to Plex...

You are about to create [anime] genre collection tags for the library [Anime] on your server [Falken].With prefix [*].
Continue? y/n... y
Found 872 media entries under Anime (133/872 completed).
Estimated time to completion: 198 minutes...

Traceback (most recent call last):---------------------------| 15.4% Complete
  File "./plex-auto-genres.py", line 22, in <module>
    UPDATE_COUNT = generate(plex)
  File "/tmp/plex-auto-genres/src/plex.py", line 75, in generate
    genres = getGenres(media, TYPE)
  File "/tmp/plex-auto-genres/src/genres.py", line 49, in getGenres
    genres = getAnimeGenres(media.title)
  File "/tmp/plex-auto-genres/src/genres.py", line 15, in getAnimeGenres
    animeId = query['results'][0]['mal_id'] # anime's MyAnimeList ID
IndexError: list index out of range

Side note, when we crash, it doesnt save progress.. so i had to stop it at 15.3% once, then try to repro so i wouldnt lose my place.

**Comment by vaparr** [comment]
i added an exception handler to getAnimeGenres(title):


```    except Exception as e:
        print(f'\n\n{str(e)}, when searching for entry: {title}')
        return []
```

And now i get this:

list index out of range, when searching for entry: Burst Angel

**Comment by ShaneIsrael** [comment]
Interesting, let me dig into this one for a minute.

**Comment by ShaneIsrael** [comment]
@vaparr Okay I believe I solved this one as well. The cause was that it couldn't find the genres for "Burst Angel" so I added a check for that. Thanks for reporting it!

**Comment by vaparr** [comment]
Thanks, I cant test it yet, after 1st run, ill see if i can delete the show from the completed.txt file, and try again. Closing for now!
